### ISSUE TITLE
irfft run on cpu device

### ISSUE THREAD

**Issue by zgyangleo** [Alexey-Kamenev/tensorrt-dft-plugins#2]
Your solution worked for me, but this is running on the GPU, do you have a way to get the ONNX runtime irfft operator to run on the CPU device?

**Comment by Alexey-Kamenev** [comment]
From what I know, ONNX FFT Contrib ops currently do not have CPU version (see [here](https://github.com/microsoft/onnxruntime/blob/e0199cfbd907e74396a5ebaaf66aa293fa512012/onnxruntime/contrib_ops/cpu/cpu_contrib_kernels.cc)). You may try asking ONNX team about this feature or possibly implement it yourself using one of the available CPU-compatible FFT libraries, like PocketFFT or other.

**Comment by zgyangleo** [comment]
thanks for your advice， i reimplement irfft cpu op with fftw in onnxruntime.

**Comment by Alexey-Kamenev** [comment]
Sounds good! And, if possible, please open PR to ONNX Runtime so other people can benefit from your work as well.
